demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from django.views import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('toupiao.urls',namespace='toupiao')),


    url(r'^static/(?P<path>.*)$', static.serve,
    {'document_root': settings.STATIC_ROOT}, name='static'),
]

demo3/toupiao/urls.py
from django.conf.urls import url
from .views import Index,List,Detail,Login,Register,LogOut,SendMail,Active,CheckUserName,VerfiyView

app_name='toupiao'

urlpatterns=[
    url(r'^$',Index.as_view(),name='index'),
    url(r'^list/(\d+)/$',List.as_view(),name='list'),
    url(r'^detail/(\d+)/$',Detail.as_view(),name='detail'),
    url(r'^login/$',Login.as_view(),name='login'),
    url(r'^register/',Register.as_view(),name='register'),
    url(r'^logout/$',LogOut.as_view(),name='logout'),
    url(r'^sendmail/$',SendMail.as_view(),name='sendmail'),
    url(r'^active/(.*?)/$',Active.as_view(),name='active'),
    url(r'^checkusername/$',CheckUserName.as_view(),name='checkusername'),
    url(r'^verify/$',VerfiyView.as_view(),name='verify')
]

demo3/toupiao/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User


class Question(models.Model):
    title=models.CharField(max_length=100)
    time=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Choice(models.Model):
    title=models.CharField(max_length=50)
    number=models.IntegerField(default=0)
    queid=models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class MyUser(User):
    telephone=models.CharField(max_length=11)

demo3/toupiao/forms.py
from django import forms
from .models import MyUser
from django.utils.translation import gettext_lazy


class LoginForm(forms.Form):
    email=forms.EmailField(label='邮箱')
    username=forms.CharField(label='用户名')
    password=forms.CharField(label='密码',widget=forms.PasswordInput)



class MyUserLoginForm(forms.ModelForm):
    class Meta():
        model=MyUser
        fields=['username','password']
        widgets={'password':forms.PasswordInput}
        help_texts={'username':gettext_lazy('')}
class MyUserRegisterForm(forms.ModelForm):
    class Meta():
        model=MyUser
        fields=['username','password','email']
        widgets={'password':forms.PasswordInput(attrs={'placeholder':'请输入密码'}),
                 'email':forms.EmailInput(attrs={'placeholder':'请输入邮箱'}),
                 'username':forms.TextInput(attrs={'placeholder':'请输入账号','required':False}),

                 }
        help_texts={'username':gettext_lazy('')}

demo3/toupiao/views.py
from django.shortcuts import render,redirect,reverse

# Create your views here.

from django.views.generic import View
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from .models import Question,Choice
from .forms import LoginForm,MyUserLoginForm,MyUserRegisterForm
from django.contrib.auth import authenticate,login,logout
from .models import MyUser
from django.core.mail import send_mail,EmailMultiAlternatives
from itsdangerous import TimedJSONWebSignatureSerializer

#用装饰器装饰一下
def checklogin(func):
    def check(self,req,*args):
        #cookie写法
        # if req.COOKIES.get('username'):
        #session写法
        # if req.session.get('username'):
        if req.user and req.user.is_authenticated:
            # print(req.COOKIES)  #{'username': 'admin'}
            # print(req.session)
            #<django.contrib.sessions.backends.db.SessionStore object at 0x000001F3BC874390>
            return func(self,req,*args)
        else:
            return redirect(reverse('toupiao:login'))
    return check

class Index(View):
    @checklogin
    def get(self,req):
        questions=Question.objects.all()
        user=req.user
        return render(req,'toupiao/index.html',locals())


class List(View):
    @checklogin
    def get(self,req,id):
        question=Question.objects.get(pk=id)
        return render(req,'toupiao/list.html',locals())
    def post(self,req,id):
        c_id=req.POST.get('f')
        choice=Choice.objects.get(pk=c_id)
        choice.number+=1
        choice.save()
        return redirect(reverse('toupiao:detail',args=(id,)))

class Detail(View):
    @checklogin
    def get(self,req,id):
        question=Question.objects.get(pk=id)
        return render(req,'toupiao/detail.html',locals())
        # return HttpResponse('%s'%(question,))

class Login(View):
    def get(self,req):
        lf=MyUserLoginForm()
        rf=MyUserRegisterForm()

        # from django.conf import settings
        # mail=EmailMultiAlternatives('测试邮件','<h1><a href="www.baidu.com">百度</a><h1>',settings.DEFAULT_FROM_EMAIL,['email'])
        # mail.content_subtype='html'
        # mail.send()


        return render(req,'toupiao/login.html',locals())
    def post(self,req):
        username=req.POST.get('username')
        password=req.POST.get('password')
        verify=req.POST.get('id_verify')
        #cookie写法
        # res=redirect(reverse('toupiao:index'))
        # res.set_cookie('username',username)
        # return res

        #session写法
        # req.session['username']=username
        # return redirect(reverse('toupiao:index'))

        #使用django自带授权系统，如果授权成功，返回user

        # user=authenticate(req,username=username,password=password)
        # if user:
        #     login(req,user)
        #     return redirect(reverse('toupiao:index'))

        user = MyUser.objects.filter(username=username).first()
        if user:
            if user.check_password(password):
                # user1 = authenticate(req, username=username, password=password)
                if user.is_active:
                    # if verify == req.session.get('verifycode'):
                    from django.core.cache import cache
                    if verify == cache.get('verifycode'):
                        user1=authenticate(req,username=username,password=password)
                        login(req, user1)
                        return redirect(reverse('toupiao:index'))
                    else:
                        lf = MyUserLoginForm()
                        errormessage = '验证码错误'
                        return render(req, 'toupiao/login.html', locals())
                else:
                    lf = MyUserLoginForm()
                    errormessage = '账号未激活'
                    return render(req,'toupiao/login.html',locals())
            else:
                lf = MyUserLoginForm()
                errormessage = '密码不正确'
                return render(req,'toupiao/login.html',locals())
        else:
            lf = MyUserLoginForm()
            errormessage = '用户名不存在'
            return render(req,'toupiao/login.html',locals())


class Register(View):
    def get(self,req):
        rf=MyUserRegisterForm()
        return render(req,'toupiao/register.html',locals())
    def post(self,req):
        try:
            username=req.POST.get('username')
            password=req.POST.get('password')
            email=req.POST.get('email')
            # print(username,password,email)
            # user=MyUser.objects.create_user(username=username,email=email,password=password)
            # return redirect(reverse('toupiao:index'))
            user=MyUser.objects.create_user(username=username,email=email,password=password)
            user.is_active=False
            user.save()

            from django.conf import settings
            userid = user.id
            util=TimedJSONWebSignatureSerializer(secret_key=settings.SECRET_KEY)
            userid=util.dumps({'userid':userid}).decode('utf-8')


            info='<a href="http://127.0.0.1:8000/active/%s/">点击激活</a>'%(userid,)
            from django.conf import settings
            mail=EmailMultiAlternatives('请激活',info,from_email=settings.DEFAULT_FROM_EMAIL,to=['18339955260@163.com'])
            mail.content_subtype='html'
            mail.send()

            if user:
                return redirect(reverse("toupiao:login"))
        except:
            lf=MyUserLoginForm()
            errormessage1='注册失败...'
            return render(req,'toupiao/login.html',locals())


class LogOut(View):
    def get(self,req):
        logout(req)
        return redirect(reverse('toupiao:login'))

class Active(View):
    def get(self,req,id):
        from django.conf import settings
        util=TimedJSONWebSignatureSerializer(secret_key=settings.SECRET_KEY)
        #这里是loads，否则会出错，写load不对
        obj=util.loads(id)
        newid=obj['userid']
        user=MyUser.objects.filter(pk=newid).first()
        if user:
            user.is_active=True
            user.save()
            return redirect(reverse('toupiao:login'))

class CheckUserName(View):
    def get(self,req):
        username=req.GET.get('username')
        user=MyUser.objects.filter(username=username).first()
        if user:
            return JsonResponse({'statecode':'1'})
        else:
            return JsonResponse({'statecode':'0','error':'用户名不存在'})

import random
from PIL import Image,ImageDraw,ImageFont
import io
class VerfiyView(View):
    def get(self,req):
        # 定义变量，用于画面的背景色、宽、高
        bgcolor = (random.randrange(20, 100),
                   random.randrange(20, 100),
                   random.randrange(20, 100))
        width = 100
        heigth = 25
        # 创建画面对象
        im = Image.new('RGB', (width, heigth), bgcolor)
        # 创建画笔对象
        draw = ImageDraw.Draw(im)
        # 调用画笔的point()函数绘制噪点
        for i in range(0, 100):
            xy = (random.randrange(0, width), random.randrange(0, heigth))
            fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
            draw.point(xy, fill=fill)
        # 定义验证码的备选值
        str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
        # 随机选取4个值作为验证码
        rand_str = ''
        for i in range(0, 4):
            rand_str += str1[random.randrange(0, len(str1))]
        # 构造字体对象
        font = ImageFont.truetype('calibri.ttf', 23)
        fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
        # 绘制4个字
        draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
        draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
        draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
        draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
        # 释放画笔
        del draw
        # req.session['verifycode'] = rand_str

        from django.core.cache import cache
        cache.set('verifycode',rand_str)

        f = io.BytesIO()
        im.save(f, 'png')
        # 将内存中的图片数据返回给客户端，MIME类型为图片png
        return HttpResponse(f.getvalue(), 'image/png')


#发送测试邮件
from django.core.mail import send_mail,EmailMultiAlternatives
from django.conf import settings
class SendMail(View):
    def get(self,req):
        try:
            #普通的发送邮件
            # send_mail('测试邮件','<h1>正文</h1>',settings.DEFAULT_FROM_EMAIL,['18339955260@163.com'])

            #新写法，可以发送HTML格式
            mail=EmailMultiAlternatives(subject='新格式邮件',body='<h1><a href="http://www.baidu.com">百度</a></h1>',from_email=settings.DEFAULT_FROM_EMAIL,to=['18339955260@163.com'])
            mail.content_subtype='html'
            mail.send()

            return HttpResponse('发送成功')
        except:
            return HttpResponse('发送失败')

demo3/templates/toupiao/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}  {% endblock %}</title>
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">-->
<!--    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>-->

    {% block link %} {% endblock %}
<!--    不加上这句话写的jQuery没有效果-->
    <script src="http://libs.baidu.com/jquery/2.1.4/jquery.min.js"></script>

</head>
<body>
{% block body %}  {% endblock %}
{% block script %}{% endblock %}
</body>
</html>

demo3/templates/toupiao/detail.html
{% extends 'toupiao/base.html' %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--    <link rel="stylesheet" href="/static/main.css">-->

<!--</head>-->
<!--<body>-->
<!--<div class="container">-->
<!--    <h2>投票结果</h2>-->
<!--    <h2>问题</h2>-->
<!--    {{question}}-->
<!--    <h2>票数</h2>-->
<!--    {% for choice in question.choice_set.all %}-->
<!--        <ul>-->
<!--            <li>{{choice.title}}-&ndash;&gt;{{choice.number}}</li>-->
<!--        </ul>-->
<!--    {% endfor %}-->
<!--    <a href="{% url 'toupiao:index' %}">返回首页</a>-->
<!--</div>-->
<!--</body>-->
<!--</html>-->

{% block title %}首页{% endblock %}
{% block link %}<link rel="stylesheet" href="/static/main.css">{% endblock %}

{% block body %}
<div class="container">
    <h2>投票结果</h2>
    <h2>问题</h2>
    {{question}}
    <h2>票数</h2>
    {% for choice in question.choice_set.all %}
        <ul>
            <li>{{choice.title}}--->{{choice.number}}</li>
        </ul>
    {% endfor %}
    <a href="{% url 'toupiao:index' %}">返回首页</a>
</div>
{% endblock %}

demo3/templates/toupiao/index.html
{% extends 'toupiao/base.html' %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>首页</title>-->
<!--    <link rel="stylesheet" href="/static/main.css">-->
<!--</head>-->
<!--<body>-->
<!--<div class="container">-->
<!--    <h2>首页</h2>-->


<!--&lt;!&ndash;    <h2>首首页</h2>&ndash;&gt;-->
<!--    {# 单行注释以及多行注释 #}-->
<!--    {# <h2>首首首页</h2> #}-->
<!--    {% comment %}-->
<!--    我-->
<!--    我-->
<!--    我-->
<!--    我-->
<!--    我-->
<!--    {% endcomment %}-->

<!--    <h3>问题详情</h3>-->
<!--    {% for question in questions %}-->
<!--        <ul>-->
<!--            <li>{{forloop.counter}}&nbsp&nbsp<a href="{% url 'toupiao:list' question.id %}">{{question.title}}</a></li>-->
<!--        </ul>-->
<!--    {% endfor %}-->
<!--</div>-->
<!--</body>-->
<!--</html>-->




{% block title %}首页{% endblock %}
{% block link %}<link rel="stylesheet" href="/static/main.css">{% endblock %}
{% block body %}
<div class="container">
    <h2>首页</h2>
    <h2>用户{{user}}----<a href="{% url 'toupiao:logout' %}">退出</a></h2>
    <h3>问题详情</h3>
    {% for question in questions %}
        <ul>
            <li>{{forloop.counter}}&nbsp&nbsp<a href="{% url 'toupiao:list' question.id %}">{{question.title}}</a></li>
        </ul>
    {% endfor %}
</div>
{% endblock %}

demo3/templates/toupiao/list.html
{% extends 'toupiao/base.html' %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>list</title>-->
<!--    <link rel="stylesheet" href="/static/main.css">-->
<!--</head>-->
<!--<body>-->
<!--<div class="container">-->
<!--    <h2>问题</h2>-->
<!--    {{question}}-->
<!--    <h2>请选择</h2>-->
<!--    <form action="{% url 'toupiao:list' question.id %}" method="post">-->
<!--        {% csrf_token %}-->
<!--        <ul>-->
<!--        {% for choice in question.choice_set.all %}-->
<!--            {% if forloop.counter == 1 %}-->
<!--                <li><input type="radio" checked name="f" value="{{choice.id}}">{{choice.title}}</li>-->
<!--            {% else %}-->
<!--                <li><input type="radio" name="f" value="{{choice.id}}">{{choice.title}}</li>-->
<!--            {% endif %}-->
<!--        {% endfor %}-->
<!--        </ul>-->
<!--        <input type="submit" value="提交">-->
<!--    </form>-->

<!--</div>-->
<!--</body>-->
<!--</html>-->


{% block title %}首页{% endblock %}
{% block link %}<link rel="stylesheet" href="/static/main.css">{% endblock %}
{% block body %}
<div class="container">
    <h2>问题</h2>
    {{question}}
    <h2>请选择</h2>
    <form action="{% url 'toupiao:list' question.id %}" method="post">
        {% csrf_token %}
        <ul>
        {% for choice in question.choice_set.all %}
            {% if forloop.counter == 1 %}
                <li><input type="radio" checked name="f" value="{{choice.id}}">{{choice.title}}</li>
            {% else %}
                <li><input type="radio" name="f" value="{{choice.id}}">{{choice.title}}</li>
            {% endif %}
        {% endfor %}
        </ul>
        <input type="submit" value="提交">
    </form>
</div>>
{% endblock %}

demo3/templates/toupiao/login.html
{% extends 'toupiao/base.html' %}


{% block link %}
<link rel="stylesheet" href="/static/main.css">
{% endblock %}


{% block script %}
<script src="/static/main.js"></script>

<script>
    $(function(){
        $("#myimg").click(function(){
            console.log('111');
<!--            这里src后面必须是逗号，否则会出错-->
            $("#myimg").attr('src','/verify/?t='+new Date().getTime())
        })


        $("#id_username").blur(function(){
            $.ajax({
                type:'get',
                url:"/checkusername/?username="+$("#id_username").val(),
                success:function(data){
                    console.log(data);
                    if(data['statecode']==0)
                    {
                        $("#errorinfo").text(data['error'])
                    }
                }
            })
        })
    })

</script>
{% endblock %}



{% block body %}
<div class="container">
    <h2>登录</h2>
    <h2>{{errormessage}}</h2>
    <h2>{{errormessage1}}</h2>
    <h2><a href="{% url 'toupiao:register' %}">注册</a></h2>
    <form action="{% url 'toupiao:login' %}" method="post">
        <p id="errorinfo"></p>
        {% csrf_token %}
        {{lf}}

        <label for="id_verify">验证码</label><img id="myimg" src="{% url 'toupiao:verify' %}" width='100' height='30' alt="">
        <input type="text" name="id_verify" id="id_verify">
        <input type="submit" value="提交">
    </form>
    <br>
    <br>
    <br>
</div>
{% endblock %}

demo3/templates/toupiao/register.html
{% extends 'toupiao/base.html' %}

{% block link %}
<link rel="stylesheet" href="/static/main.css">
{% endblock %}


{% block body %}
<div class="container">
    <h2>欢迎来到注册界面</h2>
    <form action="{% url 'toupiao:register' %}" method="post">
        {% csrf_token %}
        {{rf}}
        <br><br><br><br><br>
        <input type="submit" value="提交">
    </form>
    <a href="{% url 'toupiao:login' %}"><h2>返回登录界面</h2></a>
    <br>
    <br>
    <br>
</div>


{% endblock %}