demo4/blog/urls.py
from . import views
from django.conf.urls import url
from .feed import ArticleFeed
from haystack.views import SearchView

from django.views import static
from django.conf import settings

app_name='blog'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^$',views.index,name='index'),
    url(r'^single/(\d+)/$',views.SingleView.as_view(),name='single'),
    url(r'^archieves/(\d+)/(\d+)/$',views.ArchieveView.as_view(),name='archieve'),
    url(r'^category/(\d+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(\d+)/$',views.TagView.as_view(),name='tag'),
    url(r'^rss/$',ArticleFeed(),name='rss'),
    url(r'^contact/$',views.ContactView.as_view(),name='contact'),
    url(r'^search/$',SearchView(),name='search'),

    # url(r'^static/(?P<path>.*)$', static.serve,
    # {'document_root': settings.STATIC_ROOT}, name='static'),
]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('blog.urls',namespace='blog')),
]

demo4/blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from tinymce.models import HTMLField


#标签表
class Tag(models.Model):
    #和文章表之间的关系：多对多
    #标签名
    title=models.CharField(max_length=50)

    def __str__(self):
        return self.title

#分类表
class Category(models.Model):
    #和文章之间的关系：一对多
    #类名
    title=models.CharField(max_length=50)

    def __str__(self):
        return self.title

#文章表
class Article(models.Model):
    #文章标题
    title=models.CharField(max_length=50)
    #作者
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    #内容，比较多，使用textfield
    body=models.TextField()
    #创建时间，自动填充
    create_time=models.DateTimeField(auto_now=True)
    #更新时间
    update_tiem=models.DateTimeField(auto_now_add=True)
    #浏览数
    views=models.IntegerField(default=0)
    #分类表
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    h=models.ManyToManyField(Tag)


    def __str__(self):
        return self.title


class Ads(models.Model):
    pic=models.ImageField(upload_to='ads')
    desc=models.CharField(max_length=20)
    url=models.CharField(max_length=20)

    def __str__(self):
        return self.desc


class MessageInfo(models.Model):
    email=models.EmailField()
    info=HTMLField()

    def __str__(self):
        return self.email

demo4/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse

# Create your views here.

from .models import *
from comments.forms import CommentForm
from django.http import HttpResponse
from comments.models import Comment
from django.core.paginator import Paginator
import markdown

#用视图类写
from django.views.generic import View


#提取公共方法
class Luyou:
    def aaa(self,req,articles):
        paginator = Paginator(articles, 1)
        pagenum = req.GET.get('page')
        pagenum = 1 if pagenum == None else pagenum
        page = paginator.get_page(pagenum)
        return page



class IndexView(View):
    def get(self,req):
        # articles=Article.objects.all()
        articles=Article.objects.get_queryset().order_by('id')

        # from django.core.paginator import Paginator
        # 得到分页
        # paginator = Paginator(articles,2)
        # print(paginator.count)
        # print(paginator.object_list)
        # print(paginator.num_pages)
        # print(paginator.page_range)
        # # 得到页面
        # page = paginator.get_page(3)
        # print(page.object_list)
        # # 由页面得到分页    分页可以得到页面  页面可以得到分页

        # paginator=Paginator(articles,1)   #对从数据库中获得的所有文章进行分页

        # print(paginator.count)       #文章的个数
        # print(paginator.object_list)  #获取文章的列表，显示一个queryset列表，只显示标题
        # print(paginator.num_pages)    #一共有多少页
        # print(paginator.page_range)    #range(1,3)---1,2

        # pagenum=req.GET.get('page')
        # pagenum=1 if pagenum==None else pagenum
        #
        # page=paginator.get_page(pagenum)
        #
        # # page.path='/'
        # page.path=reverse('blog:index')
        #
        # return render(req,'blog/index.html',{'page':page})

        luyou=Luyou()
        page=luyou.aaa(req,articles)
        page.path = reverse('blog:index')
        return render(req,'blog/index.html',{'page':page})


# #这里注意使用视图类效果出不来，使用视图函数
# from django.views.decorators.cache import cache_page
# #使用这个装饰器对首页进行缓存
# @cache_page(60*5)
# def index(req):
#     articles = Article.objects.get_queryset().order_by('id')
#     luyou = Luyou()
#     page = luyou.aaa(req, articles)
#     page.path = reverse('blog:index')
#     return render(req, 'blog/index.html', {'page': page})



class SingleView(View):
    def get(self,req,id):
        # article=Article.objects.get(pk=id)
        article=get_object_or_404(Article,pk=id)

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])#这里不加引号会报错

        article.body=md.convert(article.body)
        article.toc=md.toc

        cf=CommentForm()
        return render(req,'blog/single.html',locals())
    def post(self,req,id):
        # name=req.POST.get('name')
        # email=req.POST.get('email')
        # url=req.POST.get('url')
        # content=req.POST.get('content')

        cf=CommentForm(req.POST)
        print(cf)
        if cf.is_valid():
            res=cf.save(commit=False)
            res.article=get_object_or_404(Article,pk=id)
            res.save()
            return redirect(reverse('blog:single',args=(id,)))

#归档视图类
class ArchieveView(View):
    def get(self,req,year,month):
        # articles=Article.objects.filter(create_time__year=year,create_time__month=month)
        articles=Article.objects.get_queryset().order_by('id').filter(create_time__year=year,create_time__month=month)

        # paginator=Paginator(articles,1)
        # pagenum=req.GET.get('page')
        # pagenum=1 if pagenum==None else pagenum
        # page=paginator.get_page(pagenum)
        # # page.path='/archieve/%s/%s'%(year,month)
        # page.path=reverse('blog:archieve',args=(year,month))
        # return render(req,'blog/index.html',{'page':page})

        luyou = Luyou()
        page = luyou.aaa(req, articles)
        page.path = reverse('blog:archieve', args=(year, month))
        return render(req,'blog/index.html',{'page':page})



class CategoryView(View):
    def get(self,req,id):
        category=get_object_or_404(Category,pk=id)
        # articles=category.article_set.all()
        articles=category.article_set.get_queryset().order_by('id')


        # paginator = Paginator(articles, 1)
        # pagenum = req.GET.get('page')
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # # page.path = '/category/%s' % (id)
        # page.path =reverse('blog:category',args=(id,))
        # return render(req,'blog/index.html',{'page':page})

        luyou = Luyou()
        page = luyou.aaa(req, articles)
        page.path =reverse('blog:category',args=(id,))
        return render(req,'blog/index.html',{'page':page})



class TagView(View):
    def get(self,req,id):
        tag=get_object_or_404(Tag,pk=id)
        # articles=tag.article_set.all()
        articles=tag.article_set.get_queryset().order_by('id')

        # paginator = Paginator(articles, 1)
        # pagenum = req.GET.get('page')
        # pagenum = 1 if pagenum == None else pagenum
        # page = paginator.get_page(pagenum)
        # # page.path = '/tag/%s' % (id)
        # page.path = reverse('blog:tag',args=(id,))
        # return render(req,'blog/index.html',{'page':page})

        luyou = Luyou()
        page=luyou.aaa(req,articles)
        page.path = reverse('blog:tag',args=(id,))
        return render(req,'blog/index.html',{'page':page})

class ContactView(View):
    def get(self,req):
        return render(req,'blog/contact.html')
    def post(self,req):
        email=req.POST.get('email')
        message=req.POST.get('message')
        info=MessageInfo()
        info.email=email
        info.message=message
        info.save()
        return HttpResponse('建议成功')

demo4/templates/blog/base.html
<!DOCTYPE html>
{% load my_fun %}

<html>
<head>
    <title>{% block title %} {% endblock %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/blog/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/blog/css/pace.css">
    <link rel="stylesheet" href="/static/blog/css/custom.css">

    <!-- js -->
    <script src="/static/blog/js/jquery-2.1.3.min.js"></script>
    <script src="/static/blog/js/bootstrap.min.js"></script>
    <script src="/static/blog/js/pace.min.js"></script>
    <script src="/static/blog/js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" placeholder="搜索" name="q" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block right %}

                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% block article %}

                        {% endblock %}
<!--                        <li>-->
<!--                            <a href="#">Django 博客开发入门教程：前言</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#">部署 Django 博客</a>-->
<!--                        </li>-->
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getarchieves as archieves %}
                        {% for archieve in archieves %}
                            <li>
                                <a href="{% url 'blog:archieve' archieve.year archieve.month %}">{{archieve.year}}年{{archieve.month}}日</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as categorys %}
                        {% for category in categorys %}
                            <li>
                                <a href="{% url 'blog:category' category.id %}">{{category.title}}<span class="post-count">({{category.article_set.count}})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for tag in tags %}
                            <li>
                                <a href="{% url 'blog:tag' tag.id %}">{{tag.title}}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/blog/js/script.js"></script>

</body>
</html>

demo4/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css">
		<link rel="stylesheet" href="/static/css/ionicons.min.css">
		<link rel="stylesheet" href="/static/css/pace.css">
	    <link rel="stylesheet" href="/static/css/custom.css">

	    <!-- js -->
	    <script src="/static/js/jquery-2.1.3.min.js"></script>
	    <script src="/static/js/bootstrap.min.js"></script>
	    <script src="/static/js/pace.min.js"></script>
	    <script src="/static/js/modernizr.custom.js"></script>



		<script src="/static/tiny_mce/tiny_mce.js"></script>
		<script type="text/javascript">
			tinyMCE.init({
			'mode':'textareas',
			'theme':'advanced',
<!--			这里的100%必须是个字符串形式的，否则效果会错-->
			'width':'100%',
			'height':500
			});
		</script>

	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'blog:contact' %}" method="post" class="contact-form">
									{% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
<!--											<input type="text" name="name" placeholder="Name" required>-->
											<input type="email" name="email" placeholder="Email" required>
<!--											<input type="text" name="subject" placeholder="Subject" required>-->
											<textarea name="message" rows="7" placeholder="Your Message"></textarea>
<!--											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>-->
											<input type="submit" value="Drop Me a Line">
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="/static/js/script.js"></script>
		
	</body>
</html>