demo4/blog/urls.py
from . import views
from django.conf.urls import url
from .feed import ArticleFeed
from haystack.views import SearchView

from django.views import static
from django.conf import settings

app_name='blog'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='index'),
    # url(r'^$',views.index,name='index'),
    url(r'^single/(\d+)/$',views.SingleView.as_view(),name='single'),
    url(r'^archieves/(\d+)/(\d+)/$',views.ArchieveView.as_view(),name='archieve'),
    url(r'^category/(\d+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(\d+)/$',views.TagView.as_view(),name='tag'),
    url(r'^rss/$',ArticleFeed(),name='rss'),
    url(r'^contact/$',views.ContactView.as_view(),name='contact'),
    url(r'^search/$',SearchView(),name='search'),

    # url(r'^static/(?P<path>.*)$', static.serve,
    # {'document_root': settings.STATIC_ROOT}, name='static'),
]

demo4/demo4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('blog.urls',namespace='blog')),
]

demo4/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>检索</title>
</head>
<body>
<h1>检索字段：{{query}}</h1>
<h1>检索结果：</h1>
{% for a in page.object_list %}
    <ul>
        <li><a href="{% url 'blog:single' a.object.id %}">{{a.object.title}}</a></li>
    </ul>
{% endfor %}
<h2><a href="{% url 'blog:index' %}">返回首页</a></h2>
</body>
</html>